language: go

go:
  - 1.8.3

jobs:
  include:
    - stage: Check headers
      script: make check-headers
    - stage: Check go files
      script: make check-code
    - stage: Compile
      script: make compile
    - stage: CI
      script: make ci
