language: go

go:
  - 1.8.3

service:
  - docker

sudo: required

before_install:
  - docker build -t eg_sshd test
  - docker run --rm -p 6666:22 -d --name test_sshd eg_sshd

jobs:
  include:
    - stage: Check headers
      script: make check-headers
    - stage: Check go files
      script: make check-code
    - stage: Compile
      script: make compile
    - stage: CI
      script: make ci
